# Generated by Django 4.2.2 on 2023-08-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
